[package]
name = "kanto-launcher"
version = "0.1.0"
description = "Guided installer and updater for Kanto"
authors = ["Kanto contributors"]
edition = "2024"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "kanto_launcher_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
kanto-release = { path = "../../../crates/kanto-release" }
tauri-plugin-kanto-device = { path = "../../../plugins" }
reqwest = { version = "0.13", default-features = false, features = ["json", "rustls"] }
serde = { version = "1", features = ["derive"] }
tauri-plugin-opener = "2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
futures = { version = "0.3", default-features = false, features = ["std"] }
idevice = { git = "https://github.com/jkcoxson/idevice", rev = "5171e34e3a236842af1160a84d955d037ddca3af", default-features = false, features = ["full", "ring"] }
keyring = "4.2"
plume_core = { git = "https://github.com/claration/Impactor", rev = "79c72e9762ffc7886201e34ba0068f6fbeae5403", features = ["tweaks"] }
plume_store = { git = "https://github.com/claration/Impactor", rev = "79c72e9762ffc7886201e34ba0068f6fbeae5403" }
plume_utils = { git = "https://github.com/claration/Impactor", rev = "79c72e9762ffc7886201e34ba0068f6fbeae5403" }
rustls = { version = "0.23", default-features = false, features = ["std", "tls12", "ring"] }
serde_json = "1"
tempfile = "3"
